### PR TITLE
[0.16.x] fix: set `confluent.ccloudConnectionAvailable` during Resources view loading to correct Topic & Schemas view states

### LINKED ISSUE #225: "Connect to Confluent Cloud" empty-state buttons appear when opening new window and already signed in to CCloud
image

Current workaround is to click a Kafka or Schema Registry cluster and populate those views manually, but we should be able to update the view states on initial load.

### PR DESCRIPTION
**Pull request by shouples**
## Summary of Changes

Fixes #225 by setting `confluent.ccloudConnectionAvailable` whenever we check for a CCloud connection during the loading of the Resource view's tree items.

## Pull request checklist

Please check if your PR fulfills the following (if applicable):

##### Tests

- [ ] Added new
- [ ] Updated existing
- [ ] Deleted existing

##### Other

- [x] Does anything in this PR need to be mentioned in the user-facing [CHANGELOG](https://github.com/confluentinc/vscode/blob/main/CHANGELOG.md) or [README](https://github.com/confluentinc/vscode/blob/main/public/README.md)?
- [x] Have you validated this change locally by [packaging](https://github.com/confluentinc/vscode/blob/main/README.md#packaging-steps) and installing the extension `.vsix` file?
  ```shell
  gulp clicktest
  ```

### CODE REVIEW

File: src/viewProviders/resources.ts [hunk 1]
```diff
@@ -63,13 +66,8 @@ export class ResourceViewProvider implements vscode.TreeDataProvider<ResourceVie
     this.treeView = vscode.window.createTreeView("confluent-resources", { treeDataProvider: this });
 
     ccloudConnected.event((connected: boolean) => {
+      logger.debug("ccloudConnected event fired", { connected });
       this.refresh();
-      // toggle Topics/Schemas views' visibility based on connection status
```
Comment (shouples) [inline src/viewProviders/resources.ts:67]: The problem with this placement was that we would only set it during a `ccloudConnected` change event from the auth provider. 

Context: The main reason we pushed `ccloudConnected` deep into multiple condition checks in the auth provider's `getSessions()` was so we wouldn't end up calling the view provider's `.refresh()` over and over in the different views. We can safely move the `setContext` command into a more-frequently-called spot since it won't cause the UI to update unless the value actually changes.

File: src/viewProviders/schemas.ts [hunk 2]
```diff
@@ -47,7 +47,7 @@ export class SchemasViewProvider implements vscode.TreeDataProvider<SchemasViewP
     ccloudConnected.event((connected: boolean) => {
       // TODO(shoup): check this for CCloud vs local once we start supporting local SR; check the
       // TopicViewProvider for a similar check
-      logger.debug("ccloudConnected event fired, resetting", connected);
+      logger.debug("ccloudConnected event fired, resetting", { connected });
```
Comment (shouples) [inline src/viewProviders/schemas.ts:50]: Minor formatting change since I couldn't remember what the `false` meant in:
```
ccloudConnected event fired, resetting false
```
So we should now see:
```
ccloudConnected event fired, resetting { connected: false }
```

**Review by jlrobins — APPROVED** [review]
