### PR TITLE
fix schema evolution E2E tests

### LINKED ISSUE #2080: Fix schema evolution E2E test for deletion confirmation
https://github.com/confluentinc/vscode/pull/2027 changed how the input text was handled and added a warning modal for additional confirmation, which breaks the existing E2E test flow:
https://github.com/confluentinc/vscode/blob/a698bbf79a11993094c75252ded901f08c3ebe42/tests/e2e/specs/schemas.spec.ts#L96-L104

### PR DESCRIPTION
**Pull request by shouples**
## Summary of Changes

Partially a fix to update the schema/subject deletion behavior that changed in https://github.com/confluentinc/vscode/pull/2027, but turned into some more general cleanup and refactoring of existing tests to be less flaky, use (some existing, some new) page object models, and expand coverage to include JSON and protobuf schemas.

Now we have:
- AVRO vs JSON vs PROTOBUF schema types
- CCLOUD vs DIRECT connection types
- test scenarios:
  - basic schema upload and subject creation
  - happy path: schema evolution with existing subject, adding new schema version
  - unhappy path: invalid schema evolution with error notification, no new schema version

image

Closes #2080

## Any additional details or context that should be provided?

- The `loadFixture` utility function was renamed and repurposed to return the string contents of a file so we could use it with `.proto` fixtures
- We may want to set up a generic "confirm/cancel" utility for tests to reuse since this may quickly turn into copy/paste boilerplate fodder: https://github.com/confluentinc/vscode/blob/7adfb766899fe7e544751bf022320e4c98b0ef6a/tests/e2e/specs/schemas.spec.ts#L88-L99

## Pull request checklist

Please check if your PR fulfills the following (if applicable):

##### Tests

- [x] Added new
- [x] Updated existing
- [ ] Deleted existing

##### Other

- [ ] All new disposables (event listeners, views, channels, etc.) collected as  for eventual cleanup?

- [ ] Does anything in this PR need to be mentioned in the user-facing [CHANGELOG](https://github.com/confluentinc/vscode/blob/main/CHANGELOG.md) or [README](https://github.com/confluentinc/vscode/blob/main/public/README.md)?
- [ ] Have you validated this change locally by [packaging](https://github.com/confluentinc/vscode/blob/main/README.md#packaging-steps) and installing the extension `.vsix` file?
  ```shell
  gulp clicktest
  ```

### CODE REVIEW

File: src/quickpicks/uris.ts [hunk 1]
```diff
@@ -88,6 +88,7 @@ export async function uriQuickpick(
   });
 
   const quickPick = window.createQuickPick();
+  quickPick.ignoreFocusOut = true;
```
Comment (shouples) [inline src/quickpicks/uris.ts:91]: Unrelated to this PR, but was helpful to enable for test debugging and is generally nice to set when in a multi-step quickpick flow.

File: tests/e2e/objects/quickInputs/Quickpick.ts [hunk 2]
```diff
@@ -11,6 +11,18 @@ export class Quickpick {
...
+  get header(): Locator {
+    return this.locator.locator(".quick-input-header");
+  }
+
+  /** The quickpick input field where you can type to filter items. */
+  get textInput(): Locator {
+    return this.header.locator(
+      ".quick-input-and-message .quick-input-filter .quick-input-box .monaco-findInput .monaco-inputbox .ibwrapper input.input",
+    );
+  }
```
Comment (shouples) [inline tests/e2e/objects/quickInputs/Quickpick.ts:24]: Might be able to simplify this; currently only used to filter commands from the palette in `executeVSCodeCommand()`

File: tests/e2e/objects/views/SchemasView.ts [hunk 3]
```diff
@@ -0,0 +1,60 @@
...
+  }
+
+  /**
+   * Get a specific subject by name.
+   * @param subjectName The name of the subject to find
+   */
+  getSubjectByName(subjectName: string): Locator {
+    return this.subjects.filter({ hasText: subjectName });
+  }
+}
```
Comment (shouples) [inline tests/e2e/objects/views/SchemasView.ts:60]: I'm on the fence about leaving this vs using `.filter` in tests directly

File: tests/e2e/specs/flinkStatement.spec.ts [hunk 4]
```diff
@@ -9,57 +9,66 @@ import {
...
-test.describe("Flink statements and statement results viewer", () => {
-  let webview: FrameLocator;
+test.describe.fixme(
+  "Flink statements and statement results viewer",
+  {
+    annotation: {
+      type: "issue",
+      description: "https://github.com/confluentinc/vscode/issues/2112",
+    },
+  },
```
Comment (shouples) [inline tests/e2e/specs/flinkStatement.spec.ts:19]: https://playwright.dev/docs/api/class-test#test-fixme

File: tests/fixtures/schemas/customer_bad_evolution.avsc [hunk 5]
```diff
@@ -1,27 +1,11 @@
...
-      "type": "string"
-    },
-    {
-      "name": "phone",
-      "type": "string"
-    },
-    {
-      "name": "age",
-      "type": "int"
     }
```
Comment (shouples) [inline tests/fixtures/schemas/customer_bad_evolution.avsc:25]: There weren't any problems with this passing the invalid/incompatible schema evolution test, but I wanted to make the "bad evolution" path very clearly invalid and consistent between the three main schema types.

File: tests/fixtures/utils.ts [hunk 6]
```diff
@@ -1,13 +1,17 @@
...
+ * output as needed.
  * @param relativePath - Path relative to the fixtures directory (e.g. 'flink-statement-results-processing/get-statement-results-1.json')
- * @returns The parsed JSON content of the fixture file
+ * @returns The string content of the file
  */
-export function loadFixture(relativePath: string): any {
+export function loadFixtureFromFile(relativePath: string): string {
   const fixturePath = path.join(__dirname, relativePath);
-  const content = fs.readFileSync(fixturePath, "utf8");
-  return JSON.parse(content);
```
Comment (shouples) [inline tests/fixtures/utils.ts:12]: Generalized to allow using with `.proto` files, which can't be JSON-parsed.

File: tests/e2e/specs/schemas.spec.ts [hunk 7]
```diff
@@ -1,238 +1,383 @@
...
+      "workbench.editor.languageDetection": false,
+      "editor.autoClosingBrackets": "never",
+      "editor.autoClosingQuotes": "never",
+      "editor.autoIndent": "none",
+      "editor.autoSurround": "never",
+      "editor.formatOnType": false,
+      "editor.insertSpaces": false,
+      "json.format.enable": false,
+      "json.validate.enable": false,
+    });
```
Comment (shouples) [inline tests/e2e/specs/schemas.spec.ts:71]: May need more adjustments here for the JSON tests that are having issues with `page.keyboard.type`:

Image

- https://playwright.dev/docs/api/class-locator#locator-fill may need a nested element to work properly
- https://playwright.dev/docs/api/class-locator#locator-press-sequentially shows the same behavior as `page.keyboard.type` above

Comment (shouples) [reply tests/e2e/specs/schemas.spec.ts]: Adjusting this setting appears to have fixed the odd newline/comma behavior:
```
"editor.acceptSuggestionOnEnter": "off",
```

File: tests/e2e/objects/views/SchemasView.ts (hunk 3 above)
Comment (shouples) [reply tests/e2e/objects/views/SchemasView.ts]: Removed in https://github.com/confluentinc/vscode/pull/2135/commits/7e34d1b2205e4fa898212a681fdbb63989961ecd

File: tests/e2e/specs/schemas.spec.ts [hunk 8]
```diff
@@ -1,238 +1,394 @@
...
+  });
 
-      await webview.locator('[id="schema_registry\\.credentials\\.api_key"]').click();
-      await page.waitForTimeout(100);
-      await page.keyboard.type(apiKey);
+  for (const [schemaType, fileExtension] of SCHEMA_TYPES) {
+    const schemaFile = `schemas/customer.${fileExtension}`;
+
+    /** Main tests covered by each connection type test block. */
+    const schemaTests = () => {
```
Comment (shouples) [inline tests/e2e/specs/schemas.spec.ts:141]: @alexeyraspopov this part feels gross to me, but I'm not sure how else we could use the same three test scenarios across the two different connection types (CCloud / direct) without introducing a conditional `beforeEach`. Any suggestions here on a cleaner test block structure?

Comment (alexeyraspopov) [reply tests/e2e/specs/schemas.spec.ts:141]: What I would change here is what considered a variable and what's constant. Currently, you put all test scenarios in a function, which then placed in "variable environment" that defines a special setup (sets up proper connection, etc). It puts a lot of focus on a wrong thing, I think.

There are definitely ways to create a matrix of `scenarios * prerequisites` that would avoid using any conditionals or cycles. But that comes with a price of verbosity and top-level config complexity. This is where I agree with Playwright docs that suggest simply using a loop.

That said, in your example, I would do the inversion of control: split prerequisite functions, make them return the same result (seems like they all can return the same page object), write tests in a loop of prerequisite functions. Avoiding before/after hooks should also help with making dependencies explicit.

```ts
async function makeCcloudConnection(page: Page): SchemaView {
  // ...
  return new SchemaView(page);
}

async function makeDirectConnection(page: Page/*, extra parameters */): SchemaView {
  // ...
  return new SchemaView(page);
}

const builders: Array<[string, (page: Page) => Promise<SchemaView>]> = [
  ['ccloud', (page) => makeCcloudConnection(page)],
  ['direct', (page) => makeDirectConnection(page/*, more params */)],
];
const schemaTypes: Array<[string, string]> = [
  ["AVRO", "avsc"],
  ["JSON", "json"],
  ["PROTOBUF", "proto"],
];

for (const [connectionType, setupConnection] of builders) {
  test.describe(`${connectionType} connection`, () => {
    for (const [schemaType, fileExtension] of schemaTypes) {
      test.describe(`${schemaType} schema`, () => {
        test(`should create a new subject and upload the first schema version`, async ({ page }) => {
          const schemaView = await setupConnection(page);
          const subjectName = await schemaView.setupSchema(schemaType, fileExtension);
          // ...
        });
  
        test(`should create a new schema version with valid/compatible changes`, async ({ page }) => {
          const schemaView = await setupConnection(page);
          const subjectName = await schemaView.setupSchema(schemaType, fileExtension);
          // ...
        });
      });
    }
  });
}
```

File: tests/e2e/specs/schemas.spec.ts [hunk 9]
```diff
@@ -1,238 +1,394 @@
...
+      await confirmationBox.input.fill(deletionConfirmation);
+      await confirmationBox.confirm();
+
+      // the system dialog is automatically handled by the stub above, no need to handle it here
+
+      const deletionNotifications = notificationArea.infoNotifications.filter({
+        hasText: /hard deleted/,
+      });
+      await expect(deletionNotifications.first()).toBeVisible();
+    }
```
Comment (shouples) [inline tests/e2e/specs/schemas.spec.ts:134]: TODO: fix this since it's currently broken when these tests run on Linux

Comment (shouples) [reply tests/e2e/specs/schemas.spec.ts:129]: Fixed in https://github.com/confluentinc/vscode/pull/2135/commits/e7c08a694f382cb330e745032ea83860ee591c82

File: tests/e2e/specs/schemas.spec.ts (hunk 8 above)
Comment (shouples) [reply tests/e2e/specs/schemas.spec.ts]: This definitely reads cleaner to me, and I just made some slight adjustments to preserve the `beforeEach` hook at that connection-specific level https://github.com/confluentinc/vscode/pull/2135/commits/b5971b9af51c358b8bb57cccaeba280e62004ea3

**Review by alexeyraspopov — APPROVED** [review]
