### PR TITLE
OAuth support in Direct Connection Form

### LINKED ISSUE #712: New Connection form should save user inputs when they leave the tab and return
Let's make it work like the scaffold form where the user can go away from the tab and come back without losing the inputs they've already filled. One exception will be any sensitive credentials (passwords, secrets) since we don't want them hanging out in the state.

### LINKED ISSUE #836: Support OAuth credentials type in CP connection form
OAuthCredentials - https://github.com/confluentinc/vscode/blob/main/src/clients/sidecar-openapi-specs/sidecar.openapi.yaml#L890-L929

### PR DESCRIPTION
**Pull request by noeldevelops**
## Summary
- New reusable web component for auth credentials - `<auth-credentials />` replaces templates and related logic for showing  fields in `direct-connect-form.html`
- Adds OAuth fields to form (inside ^) and connect them to the paths/functions required for saving them with a direct connection spec. 
- Updates the tests to cover this auth type
- Refactor: remove the previous functions that hid secrets and re-merged them. Deemed unnecessary since users have access to secrets in vscode 
- Closes #836 
- Closes #712 

### Screenshots
| Visual Studio Light |
| -- | 
| Screenshot 2025-03-11 at 9 13 25 AM | 

| Visual Studio Dark | 
| -- | 
| Screenshot 2025-03-11 at 9 14 26 AM |

### ✏️ What's next? (follow up PRs in the near future)
- Client-side validation for certain fields
- Add connection types: WarpStream, add Other text field back
- More telemetry logs

## Pull request checklist

Please check if your PR fulfills the following (if applicable):

##### Tests

- [X] Added new
- [X] Updated existing
- [X] Deleted existing

##### Other

- [x] All new disposables (event listeners, views, channels, etc.) collected as  for eventual cleanup?

- [x] Does anything in this PR need to be mentioned in the user-facing [CHANGELOG](https://github.com/confluentinc/vscode/blob/main/CHANGELOG.md) or [README](https://github.com/confluentinc/vscode/blob/main/public/README.md)?
- [ ] Have you validated this change locally by [packaging](https://github.com/confluentinc/vscode/blob/main/README.md#packaging-steps) and installing the extension `.vsix` file?
  ```shell
  gulp clicktest
  ```

### CODE REVIEW

**Review by Cerchie — COMMENTED** [review]
I appreciate the red highlights when the pattern is wrong. 

Was looking for a doc on testing OAuth, couldn't find the details in our own Confluence docs... 

what's the limit on the Connect Timeout? Mashed a bunch of 9's and didn't find one 

Screenshot 2025-03-10 at 9 17 44 AM
Screenshot 2025-03-10 at 9 17 27 AM

**Review by flippingbits — APPROVED** [review]
Thanks for the fast copy update, @noeldevelops!

**Comment by rohitsanj** [comment]
Thank you, @noeldevelops!

Some minor feedback based from our bug bash earlier:

1. For Confluent Cloud Kafka, limit auth types to API Credentials and SASL/OAUTHBEARER
2. For Confluent Cloud SR, limit auth types to API Credentials and OAuth (renamed from SASL/OAUTHBEARER)

File: src/webview/auth-credentials.ts [hunk 1]
```diff
@@ -0,0 +1,326 @@
...
+              required
+              data-attr-id="this.getInputId('hash_algorithm')"
+              data-attr-name="this.getInputId('hash_algorithm')"
+              data-value="this.creds()?.hash_algorithm ?? null"
+              data-on-input="this.updateValue(event)"
+            >
+              <option
+                value="SCRAM_SHA_256"
+                data-attr-selected="this.creds()?.hash_algorithm === 'SCRAM_SHA_256' ? true : false"
+              >
```
Comment (flippingbits) [inline src/webview/auth-credentials.ts:155]: Could we show this option as selected by default? At the moment, the select box is empty by default.

Screenshot 2025-03-11 at 18 16 22

The same feedback applies to other select boxes like those used in the TLS Configuration section.

**Review by flippingbits — COMMENTED** [review]
Great work, @noeldevelops! I have only one question. Otherwise your PR looks good to me. I click-tested the form with a few configurations.

File: src/webview/auth-credentials.ts (hunk 1 above)
Comment (noeldevelops) [reply src/webview/auth-credentials.ts:155]: yes, easy fix and a good catch. Thanks!

File: src/webview/auth-credentials.ts [hunk 2]
```diff
@@ -0,0 +1,320 @@
...
+    sheet.insertRule(`:host { display: flex; flex-direction: column; gap: 12px; width: 100%; }`);
+    sheet.insertRule(`.flex-column { display: flex; flex-direction: column; gap: 5px; }`);
+    shadow.adoptedStyleSheets = [sheet];
+    shadow.innerHTML = this.template;
+    applyBindings(shadow, this.os, this);
+  }
+}
+
+// Register the custom element
+// customElements.define("auth-credentials", AuthCredentials);
```
[the remark this answers is not in the document]
Comment (noeldevelops) [reply src/webview/auth-credentials.ts:320]: Ah, it's an example of how to register but I need to update the comment. Thanks!

**Review by shouples — APPROVED** [review]
