### PR TITLE
[v1.6.x] fix catalog/database codelens failing to match based on `name`

### LINKED ISSUE #2437: Set Pool/Catalog/DB medata when opening existing flink job
Similar to #2414, when user select an existing Flink job from "flink statement" view to open the SQL query in new editor, we should also set the metadata so that pool/catalog/db for that tab defaults to the same value the query was originally submitted.

### PR DESCRIPTION
**Pull request by shouples**
## Summary of Changes

Mostly an update to the Flink SQL codelens provider's `getCatalogDatabaseFromMetadata()` helper function since it was previously only matching catalog/database (against the user's already-loaded items in the Resources view) using `name` and returning the first match.

This was problematic because default Kafka cluster (database) names are pretty generic (e.g. `cluster_0`, `cluster_1`, etc), so it was entirely possible for multiple CCloud environments to have `cluster_0`s with different cloud provider/region combos. If the first one was found, its parent environment (catalog) would be brought along, but would then fail to match on the compute pool's cloud provider/region combo and the "Set catalog/database" placeholder codelens would show up.

Now we're explicitly checking how many matches we get based on the catalog/database `name`s, then trying to match against any available catalog/database IDs, and _then_ attempt to match based on any provided Flink compute pool cloud provider/region combo. (And if we still have multiple matches, give up and let the user disambiguate via codelens -> metadata assignment.)

Closes #2437.

## Any additional details or context that should be provided?

- In order to better match resources, it required tracking some CCloud environment (catalog) information so we could match catalog+database names instead of just the database. At the same time, we had previously discussed tracking catalog/database IDs separately from names, so this PR takes care of some of that explicit association as well.
- https://github.com/confluentinc/vscode/blob/djs/database-pool-mismatch/src/codelens/flinkSqlProvider.test.ts was restructured to better fit the `file->function->tests` hierarchy to avoid having to set up sandboxes over and over
- Minor: in order to more easily check the currently selected Flink compute pool for metadata matching and cloud provider/region fallback, I added `getFlinkComputePools()` and `getFlinkComputePool()` methods to the `CCloudResourceManager`.
- Minor: the tooltip over the catalog/database codelens now also includes the database's cloud region/provider combo
image

- While clicktesting, I realized implementing a fix for #2157 was easily doable as well, so that's included in this under the umbrella of "document metadata tracking fixes".

## Pull request checklist

Please check if your PR fulfills the following (if applicable):

##### Tests

- [x] Added new
- [x] Updated existing
- [x] Deleted existing

##### Other

- [ ] All new disposables (event listeners, views, channels, etc.) collected as  for eventual cleanup?

- [ ] Does anything in this PR need to be mentioned in the user-facing [CHANGELOG](https://github.com/confluentinc/vscode/blob/main/CHANGELOG.md) or [README](https://github.com/confluentinc/vscode/blob/main/public/README.md)?
- [x] Have you validated this change locally by [packaging](https://github.com/confluentinc/vscode/blob/main/README.md#packaging-steps) and installing the extension `.vsix` file?
  ```shell
  gulp clicktest
  ```

### CODE REVIEW

File: src/flinkSql/flinkLanguageClientManager.ts [hunk 1]
```diff
@@ -405,11 +405,14 @@ export class FlinkLanguageClientManager extends DisposableCollection {
     const uriMetadata: UriMetadata | undefined = await rm.getUriMetadata(uri);
     // If not, does the workspace have a default set?
     // Set to whichever one wins!
-    computePoolId = uriMetadata?.flinkComputePoolId ?? (FLINK_CONFIG_COMPUTE_POOL.value || null);
-    currentDatabaseId = uriMetadata?.flinkDatabaseId ?? (FLINK_CONFIG_DATABASE.value || null);
+    computePoolId =
+      uriMetadata?.[UriMetadataKeys.FLINK_COMPUTE_POOL_ID] ??
+      (FLINK_CONFIG_COMPUTE_POOL.value || null);
+    currentDatabaseName =
+      uriMetadata?.[UriMetadataKeys.FLINK_DATABASE_NAME] ?? (FLINK_CONFIG_DATABASE.value || null);
```
Comment (shouples) [inline src/flinkSql/flinkLanguageClientManager.ts:412]: cc @noeldevelops

File: src/codelens/flinkSqlProvider.test.ts [hunk 2]
```diff
@@ -20,180 +22,302 @@ import {
...
-  let ccloudLoaderStub: sinon.SinonStubbedInstance<CCloudResourceLoader>;
-  let hasCCloudAuthSessionStub: sinon.SinonStub;
 
-  // NOTE: setting up fake TextDocuments is tricky since we can't create them directly, so we're
-  // only populating the fields needed for the test and associated codebase logic, then using the
-  // `as unknown as TextDocument` pattern to appease TypeScript
-  const fakeDocument: TextDocument = { uri: testUri } as unknown as TextDocument;
+  before(async () => {
+    await getTestExtensionContext();
+  });
```
Comment (shouples) [inline src/codelens/flinkSqlProvider.test.ts:35]: This `before` hook isn't necessary, but makes using the Extension Test Runner extension much happier since it doesn't run through the global [beforeAll](https://github.com/confluentinc/vscode/blob/09b206fcd180419e256a3b63291f57e1f2ae4d77/src/testing.ts#L56-L57) that sets extension context, checks the sidecar, etc.

File: src/loaders/ccloudResourceLoader.ts [hunk 3]
```diff
@@ -128,6 +128,37 @@ export class CCloudResourceLoader extends CachingResourceLoader<
...
+   * Get a specific Flink compute pool by ID.
+   * @param computePoolId The compute pool ID to look for.
+   * @returns The {@link CCloudFlinkComputePool} with the given ID, or undefined if not found.
+   */
+  public async getFlinkComputePool(
+    computePoolId: string,
+  ): Promise<CCloudFlinkComputePool | undefined> {
+    const pools = await this.getFlinkComputePools();
+    return pools.find((p) => p.id === computePoolId);
+  }
```
[the remark this answers is not in the document]
Comment (shouples) [reply src/loaders/ccloudResourceLoader.ts:160]: ...but since that's touching compute pool metadata, probably better to handle in a separate (smaller) PR instead of mixing it up with the catalog/database work here
