### PR TITLE
MINOR: add more filters to Sentry

### LINKED ISSUE #693: Filter `Error: EPERM: operation not permitted` unless related to sidecar start or project scaffolding file creation
Sentry Issue: [VSCODE-EXTENSION-F4](https://confluent.sentry.io/issues/6092642303/?referrer=github_integration)

```
Error: EPERM: operation not permitted, lstat '...'
```

### LINKED ISSUE #796: Figure out how to remove `node_modules/**` from source mapping
We're getting some unnecessary exceptions passed to Sentry that only have source-mapped stack traces pointing at `node_modules` for:
- `@sentry/core`
- `@sentry/node`
- `@opentelemetry`

If we can prevent those from being "marked" with our [third party filter key](https://github.com/confluentinc/vscode/blob/bbb14068f243ccad17c59c6f3b1cbc3c5d41ae53/src/extension.ts#L19-L26), we (hopefully) shouldn't see them anymore
https://docs.sentry.io/platforms/javascript/configuration/filtering/#using-thirdpartyerrorfilterintegration

Details TBD - this description may need updating/clarifying

### LINKED ISSUE #866: Filter out `Canceled` errors from Sentry reporting
Sentry Issue: [VSCODE-EXTENSION-GV](https://confluent.sentry.io/issues/6204600504/?referrer=github_integration)

```
Canceled: Canceled
  File "app:///extensionHostProcess.js", line 32, in new IT
  File "app:///extensionHostProcess.js", line 32, in Dy.U
  File "app:///extensionHostProcess.js", line 32, in Proxy.s.<computed>.n.charCodeAt.s.<computed>
  File "app:///extensionHostProcess.js", line 119, in IS.get
  File "app:///extensionHostProcess.js", line 119, in SM.get
...
(9 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by shouples**
Closes #693, closes #796 (by filtering out `captureException` which we only ever see from `node_modules/@sentry/*` errors), closes #866.

### CODE REVIEW

File: src/extension.ts [hunk 1]
```diff
@@ -27,6 +27,9 @@ if (process.env.SENTRY_DSN) {
     ignoreErrors: [
       "The request failed and the interceptors did not return an alternative response",
       "ENOENT: no such file or directory",
+      "EPERM: operation not permitted",
```
Comment (shouples) [inline src/extension.ts:30]: I'm not concerned about these for sidecar process starting, since we'll see `getHandlePromise(0): failed to start sidecar` errors as well.

**Review by noeldevelops — APPROVED** [review]
