### PR TITLE
fix: preemptively clear outdated language client diagnostics

### LINKED ISSUE #1776: Diagnostics from the server don't reflect document changes
Noticed while testing in-progress branch, the errors shown by the server diagnostics don't always apply to the current doc, and sometimes seem to not realize the document has updated. Needs troubleshooting to find the root cause.

### PR DESCRIPTION
**Pull request by noeldevelops**
## Summary of Changes

- Closes #1776 
- The language server backend will intermittently fail to send the expected `publishDiagnostics` message, so in this PR we add code to manually clear out diagnostics when the doc changes, avoiding showing any outdated error messages in the UI. 

## Any additional details or context that should be provided?

- A similar workaround is in place for CCloud UI
- **To Test** 
  - Make sure the language client flag is enabled, you're logged into CCloud, and you have an open `flink.sql` document.
  - Write an invalid statement & pause until you observe the diagnostics error. 
  - Add/change the doc. Expectation: the error disappears. (Before this change, the error would not get cleared even if you corrected it in the doc)

## Pull request checklist

Please check if your PR fulfills the following (if applicable):

##### Tests

- [ ] Added new
- [ ] Updated existing
- [ ] Deleted existing

##### Other

- [X] All new disposables (event listeners, views, channels, etc.) collected as  for eventual cleanup?

- [ ] Does anything in this PR need to be mentioned in the user-facing [CHANGELOG](https://github.com/confluentinc/vscode/blob/main/CHANGELOG.md) or [README](https://github.com/confluentinc/vscode/blob/main/public/README.md)?
- [x] Have you validated this change locally by [packaging](https://github.com/confluentinc/vscode/blob/main/README.md#packaging-steps) and installing the extension `.vsix` file?
  ```shell
  gulp clicktest
  ```

### CODE REVIEW

File: src/flinkSql/languageClient.ts [hunk 1]
```diff
@@ -16,7 +16,7 @@ import { getFlinkSQLLanguageServerOutputChannel } from "./logging";
 import { WebsocketTransport } from "./websocketTransport";
 
 const logger = new Logger("flinkSql.languageClient.Client");
-
+const FLINK_DIAGNOSTIC_COLLECTION_NAME = "confluent.flinkSql";
```
Comment (flippingbits) [inline src/flinkSql/languageClient.ts:19]: nit: Keep the empty line

```suggestion
const FLINK_DIAGNOSTIC_COLLECTION_NAME = "confluent.flinkSql";

```

**Review by flippingbits — APPROVED** [review]
Thanks, @noeldevelops! Looks good to me from reading and playing with it.
