### PR TITLE
Indicate Docker Engine availability / existence in the Local Connection row

### LINKED ISSUE #2779: Make better use of knowledge of if Docker Desktop is available
When the docker service probes are failing ('cause Docker not running at all), have a new boolean context value along lines of `dockerAvailable`, and if is false, then have the Local connection row in the Resources view description say '(Docker Not Available)' instead of '(Not Running)' and have its tooltip explain "Docker service is not detected -- start up or install Docker Desktop". And not offer the 'Start' button.

When the context value is true, then should work as is now.

End goal is to not mistakenly lure the user into trying to start local services when we know they will fail.

While in here, also please make the docker service probe logs drop to `trace` level, not `debug`. They noisy.

### PR DESCRIPTION
**Pull request by jlrobins**
## Summary of Changes

- New contextvalue `dockerServiceAvailable` describing if Docker Engine has been detected as available on the users's computer.
- New event emitter `dockerServiceAvailable` firing when said context value changes. 
- Use the above to control the "Local Connection" Resource View row's status, tooltip, and 'play button' CTA to accurately describe when a Docker Engine (or sufficiently compatible) system is NOT detected, and to stop inviting users to try to start up local containers when there's no Docker Engine to run them.
- The Resources view observes the  `dockerServiceAvailable` event, and repaints the Local Connection row when it fires (then reevaluating now more nuanced `status` and `tooltip` properties).
- Augment the code in `src/docker/eventListener.ts` to manage the new context manager and event emitter.
- Try to harden tests over `src/docker/eventListener.ts`'s `EventEmitter` by realizing that extension startup _will_ have started up an `EventEmitter`, so stop it before proceeding with these tests.

### Optional: Click-testing instructions

1. Turn off Docker Engine / Docker Desktop, then start up the extension. Notice the more informative "Local" row in the Resources view.
2. Start up Docker Engine / Desktop. Notice the Local Connection row repaint itself (sooner or later -- based on the "slow" every 15s polling frequency offset when you started it) with status and tooltip indicating that Docker services are now available.
3. Start up and / or stop local Kafka and / or schema registry. See the connection row properties mutate further.
4. Reverse any / all of the above and the connection row should end up in the proper expected state.

### Optional: Any additional details or context that should be provided?

- While here, lower the logging level used when doing the Docker route probes. This makes reading our logs more friendly for folks all around.
- Closes #2779

#### No Docker Engine running. Note no `play` button anymore.
Screenshot 2025-10-06 at 6 34 35 PM

#### Docker Engine running, but none of our containers. Have play button again.
Screenshot 2025-10-06 at 6 35 17 PM

#### Local Kafka started. Can still hit play in this case, because can still start Schema Registry.
Screenshot 2025-10-06 at 6 35 55 PM

## Pull request checklist

Please check if your PR fulfills the following (if applicable):

#### Tests

- [x] Added new
- [x] Updated existing
- [ ] Deleted existing

#### Release notes

- [x] Does anything in this PR need to be mentioned in the user-facing [CHANGELOG](https://github.com/confluentinc/vscode/blob/main/CHANGELOG.md)?

### CODE REVIEW

File: src/viewProviders/resources.ts [hunk 1]
```diff
@@ -416,7 +417,14 @@ export class LocalConnectionRow extends SingleEnvironmentConnectionRow<
...
   get tooltip(): MarkdownString {
-    return new MarkdownString("Local Kafka clusters discoverable at port `8082` are shown here.");
+    const isDockerAvailable = getContextValue(ContextValues.dockerServiceAvailable) === true;
+    if (isDockerAvailable) {
+      return new MarkdownString("Local Kafka clusters discoverable at port `8082` are shown here.");
+    } else {
+      return new MarkdownString(
+        "Docker is not available. Start (or install) Docker to control local Kafka clusters and Schema Registry here.",
+      );
+    }
```
[the remark this answers is not in the document]
Comment (jlrobins) [reply src/viewProviders/resources.ts:427]: The `getContextValue` is extraordinarily cheap. Is fine just like this.

File: CHANGELOG.md [hunk 2]
```diff
@@ -8,14 +8,21 @@ All notable changes to this extension will be documented in this file.
 
 - The Flink Artifacts / Flink UDFs view is now searchable.
 
+### Changed
+
+- The Local row in the Resources view now better describes the user's Docker Engine state in its
+  state and tooltip, and the "play" button call-to-action will not be offerred if Docker Engine is
+  not detected.
```
Comment (shouples) [inline CHANGELOG.md:15]: Minor update for clarity:
```suggestion
- The Local row in the Resources view now better describes the user's Docker Engine availability in its
  description and tooltip, and the "Start Local Resources" action will not be offered if the extension cannot ping the local Docker Engine.
```

File: src/docker/eventListener.ts [hunk 3]
```diff
@@ -54,13 +58,14 @@ export class EventListener {
     this.poller = new IntervalPoller(
       "pollDockerEvents",
       () => {
-        this.listenForEvents();
+        void this.listenForEvents();
       },
```
Comment (shouples) [inline src/docker/eventListener.ts:62]: I was on the fence about this one while working on https://github.com/confluentinc/vscode/pull/2787 - should we leave this without the `void` and (in a follow-up branch) update `IntervalPoller` to always [`await` its callback](https://github.com/confluentinc/vscode/blob/b50768ddc4992274e740b44caab3f25e8ee0ab0b/src/utils/timing.ts#L172-L175)?

**Review by shouples — APPROVED** [review]
Nice improvements here, thanks!
