### PR TITLE
Only send the rarer / harder to explain sidecar startup errors to Sentry ...

### LINKED ISSUE #2206: More precise telemetry around sidecar startup failures
There are a number of known issues when the sidecar fails to start and we handle them [here](https://github.com/confluentinc/vscode/blob/3a6a091ab34e80474a9d9413adbddeee3f6c1025/src/sidecar/utils.ts#L213) and notify the user of the reason. 
https://github.com/confluentinc/vscode/blob/3a6a091ab34e80474a9d9413adbddeee3f6c1025/src/sidecar/utils.ts#L213

To decrease the noise for VS Code On Call we'd like to minimize the events sent to Sentry when events are for well-known reasons & not actionable. We can still send the unknown reasons and/or send some events to Segment for data analysis at team discretion.

### PR DESCRIPTION
**Pull request by jlrobins**
## Summary of Changes

- Only send the rarer / harder to explain sidecar startup errors to Sentry, so as to lower oncall spiking. Log any startup reason to Segment for tracking, however.
- Closes #2206

## Any additional details or context that should be provided?

- This moves the logError call from `startSidecar()` into the now `triageSidecarStartupError()`, which conditionalizes adding in the sentry payload based on the failure reason.
- Adds in unconditoinally logging the failure reason into a new Segment event.

## Pull request checklist

Please check if your PR fulfills the following (if applicable):

##### Tests

- [ ] Added new
- [x] Updated existing
- [ ] Deleted existing

##### Other

- [ ] All new disposables (event listeners, views, channels, etc.) collected as  for eventual cleanup?

- [x] Does anything in this PR need to be mentioned in the user-facing [CHANGELOG](https://github.com/confluentinc/vscode/blob/main/CHANGELOG.md) or [README](https://github.com/confluentinc/vscode/blob/main/public/README.md)?
- [ ] Have you validated this change locally by [packaging](https://github.com/confluentinc/vscode/blob/main/README.md#packaging-steps) and installing the extension `.vsix` file?
  ```shell
  gulp clicktest
  ```

### CODE REVIEW

File: src/sidecar/utils.ts [hunk 1]
```diff
@@ -272,15 +303,34 @@ export async function showSidecarStartupErrorMessage(e: unknown): Promise<void>
...
+        userMessage = `Sidecar failed to start: ${e.message}`;
+        sendToSentry = true;
         break;
     }
 
-    void showErrorNotificationWithButtons(message, buttons);
+    // Sent all the SidecarFatalError reasons to Segment for numerical tracking.
+    logUsage(UserEvent.SidecarStartupFailure, {
+      reason: e.reason,
+    });
```
Comment (noeldevelops) [inline src/sidecar/utils.ts:314]: 📈

File: src/sidecar/utils.ts [hunk 2]
```diff
@@ -204,61 +205,91 @@ export function checkSidecarFile(executablePath: string) {
...
+  let logErrorMessage: string;
+  // What message to show the user.
+  let userMessage: string;
+
   if (e instanceof SidecarFatalError) {
-    logger.error(`showSidecarStartupErrorMessage(): ${e.message} (${e.reason})`);
+    logErrorMessage = "Sidecar startup SidecarFatalError";
+
+    // Should we report this reason to Sentry? Depends on the reason. Only
+    // send the rarer / lesser understood ones.
```
Comment (noeldevelops) [inline src/sidecar/utils.ts:235]: ✨

**Review by noeldevelops — APPROVED** [review]
