### PR TITLE
fix: reset `LOCAL` connection on managed container "start" events

### LINKED ISSUE #525: "Timed out waiting for node assignment" error 408 with local configuration changes
Whenever we activate the extension, we create a `LOCAL` connection to the sidecar. Our Docker [event listener](https://github.com/confluentinc/vscode/blob/main/src/docker/eventListener.ts) then reacts to container `start`/`die` events (for supported Docker images) by refreshing the Resources view accordingly, which then sends a GraphQL query to the sidecar to determine whether or not local resources are discoverable. (If they are, they show up under the `Local` container; otherwise, it shows `(Not running)`.)

We recently discovered that, if a user starts with a specific number of Kafka brokers (containers) and then drops to a **smaller** number of Kafka brokers during the lifetime of the extension being active (and sidecar process), the sidecar will continue to expect those previous bootstrap servers. (E.g. we see a Kafka cluster with three brokers, then drop to using a single broker.) This is then seen by the user through any topic-create actions or by refreshing the Topics view (when the local Kafka cluster is focused) as `Timed out waiting for node assignment` error notifications with a `408` error code.

This is _not_ due to recent changes with local resource management, but is behavior from older assumptions about how local connections and resource discovery happens.

Once we move to `DIRECT` connections, the extension will be responsible for sending requests to the sidecar to update the `kafka_cluster_config`'s `bootstrap_servers` property: https://github.com/confluentinc/ide-sidecar/blob/f541af00e07ec8ae88c2a492d9b9d82c04e4456f/src/generated/resources/openapi.yaml#L720-L735

### PR DESCRIPTION
**Pull request by shouples**
## Summary of Changes

Closes #525.

To avoid the sidecar caching the local Kafka cluster / SR configuration during any resource changes after the extension activates, we need to delete and recreate the connection with the new configuration.

If we don't do this, we see error responses (after local resources successfully start) when other extension actions are attempting to make requests to the (new) configuration. -- (e.g. listing topics/schemas, consuming messages, creating topics/schemas) -- but the sidecar is referencing the old configuration. This appears in a couple different ways:
- Kafka: an error 408 response with `Timed out waiting for node assignment` (only for Kafka
- Schema Registry: an error 500 response to the effect of `Connection refused: localhost/127.0.0.1:<old port>`

Now, we look discover local SR after extension activation or from a container "start" event, then we check if the new local connection `ConnectionSpec` is different from what the sidecar is already tracking, and update it if there are any changes the sidecar should be informed of.

## Pull request checklist

Please check if your PR fulfills the following (if applicable):

##### Tests

- [ ] Added new
- [ ] Updated existing
- [ ] Deleted existing

##### Other

- [ ] Does anything in this PR need to be mentioned in the user-facing [CHANGELOG](https://github.com/confluentinc/vscode/blob/main/CHANGELOG.md) or [README](https://github.com/confluentinc/vscode/blob/main/public/README.md)?
- [x] Have you validated this change locally by [packaging](https://github.com/confluentinc/vscode/blob/main/README.md#packaging-steps) and installing the extension `.vsix` file?
  ```shell
  gulp clicktest
  ```

### CODE REVIEW

File: src/docker/configs.ts [hunk 1]
```diff
@@ -32,7 +32,7 @@ export function getSocketPath(): string {
   } else {
     path = path ? path : DEFAULT_UNIX_SOCKET_PATH;
   }
-  logger.debug("using docker socket path:", { socketPath: path });
+  logger.trace("using docker socket path:", { socketPath: path });
```
Comment (shouples) [inline src/docker/configs.ts:35]: These are annoying but helpful if we need to debug local Docker requests. May remove entirely in a future PR.

File: src/docker/workflows/cp-schema-registry.ts [hunk 2]
```diff
@@ -218,7 +222,7 @@ export class ConfluentPlatformSchemaRegistryWorkflow extends LocalResourceWorkfl
     }
 
     const kafkaImageRepo: string = getLocalKafkaImageName();
-    const kafkaImageTag: string = kafkaWorkflow.imageTag;
+    const kafkaImageTag: string = getLocalKafkaImageTag();
```
Comment (shouples) [inline src/docker/workflows/cp-schema-registry.ts:225]: Unrelated-to-this-PR bug fix where we were incorrectly using the `latest` (default) tag instead of whatever was configured in the user/workspace settings.

**Review by jlrobins — APPROVED** [review]
Great stuff, and using the sidecar as the 'single source of truth' between multiple workspaces noticing the same event is clever.
