### PR TITLE
Fix schema upload success message when was normalized to a not-most-recent version.

### LINKED ISSUE #642: Schema upload new vs existing version determination can get confused
From @derek1ee :

1. Create a file named test.confluent.avsc with the following content.
```
{
  "type": "record",
  "name": "sampleRecord",
  "namespace": "com.mycorp.mynamespace",
  "doc": "Sample schema to help you get started.",
  "fields": [
    {
      "name": "my_field1",
      "type": "int",
      "doc": "doc1"
    }
  ]
}
```
2. Create a new schema using the above file.
3. Observe a new schema is created with version 1.
4. Edit "doc": "doc1" to "doc": "doc1..."  and upload to the same schema
5.  Observe version 2 created
6.  Edit "doc": "doc1..."  back to "doc": "doc1"  and upload to the same schema
7. Observe no new version is created, but the notification reads New version 1 registered... when it should say something like Normalized to version 1...

### PR DESCRIPTION
**Pull request by jlrobins**
## Summary of Changes

- Fix the schema upload success message when the uploaded schema gets normalized to an old version for the subject. We handled when it was normalized to the most recent version, just not an older one.
- Closes #642

## Pull request checklist

Please check if your PR fulfills the following (if applicable):

##### Tests

- [x] Added new
- [ ] Updated existing
- [ ] Deleted existing

##### Other

- [ ] All new disposables (event listeners, views, channels, etc.) collected as  for eventual cleanup?

- [x] Does anything in this PR need to be mentioned in the user-facing [CHANGELOG](https://github.com/confluentinc/vscode/blob/main/CHANGELOG.md) or [README](https://github.com/confluentinc/vscode/blob/main/public/README.md)?
- [x] Have you validated this change locally by [packaging](https://github.com/confluentinc/vscode/blob/main/README.md#packaging-steps) and installing the extension `.vsix` file?
  ```shell
  gulp clicktest
  ```

### CODE REVIEW

File: src/commands/schemaUpload.ts [hunk 1]
```diff
@@ -297,20 +297,18 @@ export function extractDetail(message: string): string {
...
+  newlyRegisteredVersion: number,
 ): string {
-  // todo: make this return markdown and to not induce pain for the reader. Use a header
-  // that clearly delineates the different cases, then key / value rows for the details.
-
-  if (existingVersion === undefined) {
+  if (maxExistingVersion === undefined) {
     return `Schema registered to new subject "${subject}"`;
-  } else if (existingVersion === registeredVersion) {
+  } else if (maxExistingVersion >= newlyRegisteredVersion) {
```
Comment (jlrobins) [inline src/commands/schemaUpload.ts:305]: Better var names highlight the better comparator to use. The version assigned to the newly uploaded version can well be not the most recent version.

**Review by shouples — APPROVED** [review]
