### PR TITLE
fix(E2E): integrate view searching into tests instead of scrolling for specific tree items

### LINKED ISSUE #3136: E2E bug: handle scrolling in virtualized views
When we have a lot of items in a view (e.g. topics in the Topics view or schema subjects in the Schemas view), the E2E tests don't actually scroll as expected since the items aren't in the Electron DOM if they aren't visible. 

So for these virtualized views, the tests should be able to either:
a) scroll to the right item, or
b) use the view search functionality to filter to the exact item

Near-term fix: swap out [`scrollIntoViewIfNeeded` uses](https://github.com/search?q=repo%3Aconfluentinc%2Fvscode%20scrollIntoViewIfNeeded&type=code) with more explicit scrolling, maybe wrapped in an `await expect.poll()` to loop over locator visibility.

Longer-term fix: extend `View` page object model into `SearchableView` for Resources/Topics/Schemas/etc to subclass from, where a dedicated `search` method can be properly implemented, instead of the placeholder [`clickSearch` methods](https://github.com/search?q=repo%3Aconfluentinc%2Fvscode+clickSearch&type=code).

### PR DESCRIPTION
**Pull request by shouples**
## Summary of Changes

The current `.scrollIntoViewIfNeeded()` doesn't work for virtualized views, since all tree items aren't loaded into the Electron DOM after the initial `getChildren` and subsequent `getTreeItem` calls. As a result, we need a dedicated way to look up specific items in a view when there may be many.

This PR extends the `View` page object model with a new `SearchableView` class with some helper functions to invoke the `*.search` command from the nav area, complete the text input, and return a `ViewItem` after asserting the searched item is found, reducing boilerplate needed for callers to access their targeted tree items.

(The first iteration of this attempted to manually scroll through the view and hope the target item eventually appeared, but that grew slower over time / as more items were added to the view, so the most straightforward implementation was to go with the existing search functionality, which also indirectly adds more test coverage.)

Now our E2E tests are [back to passing](https://semaphore.ci.confluent.io/branches/7eb964bd-2284-4333-85f3-8012ec716bb8), even with 400+ topics in our main test cluster and 300+ schema versions in our main environment's Schema Registry:
image

Closes #3136

### Optional: Any additional details or context that should be provided?

- This also includes more explicit waiting for views' loading states through the `progressIndicator` getter method. Without it, we would occasionally see race conditions in the test where an action would be invoked for a tree item before/during a loading state, and the command wouldn't receive the corresponding tree item resource (e.g. a `KafkaTopic` when trying to produce messages, delete the topic, etc)
  - I previously included `await expect(this.progressIndicator).toBeVisible()` before some of the `await expect(this.progressIndicator).toBeHidden()` calls, but occasionally some operations were so fast that the tests would never pick up on the progress indicator and tests would time out
- Logging updates in `baseTest.ts` are to avoid the additional noise when 1) tests failed to save extension/sidecar logs, and 2) the electron context timed out when closing (which we typically see in CI)

## Pull request checklist

Please check if your PR fulfills the following (if applicable):

#### Tests

- [ ] Added new
- [x] Updated existing
- [ ] Deleted existing

#### Release notes

- [ ] Does anything in this PR need to be mentioned in the user-facing [CHANGELOG](https://github.com/confluentinc/vscode/blob/main/CHANGELOG.md)?

### CODE REVIEW

File: tests/e2e/baseTest.ts [hunk 1]
```diff
@@ -138,20 +138,21 @@ export const test = testBase.extend<VSCodeFixtures>({
...
         new Promise((_, reject) =>
-          setTimeout(() => reject(new Error("electronApp.close() timeout after 10s")), 10000),
+          setTimeout(() => reject(new Error("electronApp.close() timeout after 5s")), 5_000),
         ),
       ]);
-    } catch (error) {
-      console.warn("Error closing electron app:", error);
-      // force-kill if needed
+    } catch {
+      console.warn("Timed out waiting for Electron to close, killing process...");
```
Comment (Cerchie) [inline tests/e2e/baseTest.ts]: nice improvement to the warning accuracy

File: tests/e2e/objects/views/TopicsView.ts [hunk 2]
```diff
@@ -45,13 +45,21 @@ export class TopicsView extends View {
   /** Click the "Refresh" nav action in the view title area. */
   async clickRefresh(): Promise<void> {
     await this.clickNavAction("Refresh");
+    // wait for any loading to complete before returning
+    await expect(this.progressIndicator).toBeHidden();
   }
```
Comment (shouples) [inline tests/e2e/objects/views/TopicsView.ts]: This may be something added to the other view models, but the Topics view provider is the only one that doesn't behave the same as the others (since it doesn't subclass from `BaseViewProvider`/`ParentedBaseViewProvider`)

File: tests/e2e/objects/views/View.ts [hunk 3]
```diff
@@ -72,3 +81,61 @@ export class View {
...
+
+  /** Search for a tree item by its label/name. */
+  async search(query: string): Promise<void> {
+    await this.ensureExpanded();
+    await expect(this.progressIndicator).toBeHidden();
+
+    // clear the "Clear Search" nav action if it's already visible
+    const clearSearchButton = this.header.getByRole("button", { name: "Clear Search" });
+    const isSearching = await clearSearchButton.isVisible();
+    if (isSearching) {
```
[the remark this answers is not in the document]
Comment (shouples) [reply tests/e2e/objects/views/View.ts]: I'll give you this one https://github.com/confluentinc/vscode/pull/3138/commits/e176fff7655d083852ab73a527bc296b9fcb637e
