### PR TITLE
MINOR: fix `window.menuStyle` setting for Windows to unblock running E2E tests

### LINKED ISSUE #2609: Fix E2E tests running on Windows (locally)
Going off of the [`tests/e2e/` commit history](https://github.com/confluentinc/vscode/commits/main/tests/e2e), starting with https://github.com/confluentinc/vscode/pull/2557 we can't run E2E tests on Windows since they error out almost immediately during the global beforeEach `page` fixture setup and don't auto-await the expected info notification. Wrapping that [`globalBeforeEach()`](https://github.com/confluentinc/vscode/blob/24490e410fdccde7c1e9bd2ae8511d82403a9e75/tests/e2e/baseTest.ts#L132) in a try/catch doesn't help:

```
[15:38:19] Starting 'e2eRun'...
Running command: npx playwright test -c tests/e2e/playwright.config.ts tests/e2e

Running 54 tests using 1 worker

  ✓  1 [setup] › ..\global.setup.ts:20:1 › setup VS Code for E2E tests (278ms)                                                                                                                                                                                                 
Setting up VS Code (stable) for E2E tests...
- Resolving version...
✔ Validated version: 1.104.0
✔ Found existing install in C:\Users\daves\confluent_dev\vscode\.vscode-test\vscode-win32-x64-archive-1.104.0
VS Code (stable) install path: C:\Users\daves\confluent_dev\vscode\.vscode-test\vscode-win32-x64-archive-1.104.0\Code.exe
win32 VS Code (stable) executable path: C:\Users\daves\confluent_dev\vscode\.vscode-test\vscode-win32-x64-archive-1.104.0\Code.exe
Test setup complete, using:
  Executable: C:\Users\daves\confluent_dev\vscode\.vscode-test\vscode-win32-x64-archive-1.104.0\Code.exe
  Extension out/ path: C:\Users\daves\confluent_dev\vscode\out
test setup cache saved to: C:\Users\daves\AppData\Local\Temp\vscode-e2e-test-setup-cache.json
     2 [stable] › confluent.spec.ts:11:3 › should activate the extension
Error in globalBeforeEach: ExpectError: expect(locator).not.toHaveCount(expected)

Locator: locator('.notifications-toasts').locator('.notification-toast-container').filter({ has: locator('.codicon-info') }).filter({ hasText: 'All installed extensions are temporarily disabled' })
Expected: not 0
Received: 0
Call log:
  - expect.not.toHaveCount with timeout 60000ms
  - waiting for locator('.notifications-toasts').locator('.notification-toast-container').filter({ has: locator('.codicon-info') }).filter({ hasText: 'All installed extensions are temporarily disabled' })
  -   locator resolved to 0 elements
  -   unexpected value "0"
  -   locator resolved to 0 elements
  -   unexpected value "0"

    at globalBeforeEach (C:\Users\daves\confluent_dev\vscode\tests\e2e\baseTest.ts:156:39)
    at Object.page (C:\Users\daves\confluent_dev\vscode\tests\e2e\baseTest.ts:130:7) {
  matcherResult: {
    actual: 0,
    expected: 0,
    message: '\x1B[2mexpect(\x1B[22m\x1B[31mlocator\x1B[39m\x1B[2m).\x1B[22mnot\x1B[2m.\x1B[22mtoHaveCount\x1B[2m(\x1B[22m\x1B[32mexpected\x1B[39m\x1B[2m)\x1B[22m\n' +
      '\n' +
      "Locator: locator('.notifications-toasts').locator('.notification-toast-container').filter({ has: locator('.codicon-info') }).filter({ hasText: 'All installed extensions are temporarily disabled' })\n" +
      'Expected: not \x1B[32m0\x1B[39m\n' +
      'Received: \x1B[31m0\x1B[39m\n' +
      'Call log:\n' +
      '  \x1B[2m- expect.not.toHaveCount with timeout 60000ms\x1B[22m\n' +
      "\x1B[2m  - waiting for locator('.notifications-toasts').locator('.notification-toast-container').filter({ has: locator('.codicon-info') }).filter({ hasText: 'All installed extensions are temporarily disabled' })\x1B[22m\n" +
      '\x1B[2m  -   locator resolved to 0 elements\x1B[22m\n' +
      '\x1B[2m  -   unexpected value "0"\x1B[22m\n' +
      '\x1B[2m  -   locator resolved to 0 elements\x1B[22m\n' +
      '\x1B[2m  -   unexpected value "0"\x1B[22m\n',
    name: 'toHaveCount',
    pass: true,
    log: [
      'expect.not.toHaveCount with timeout 60000ms',
      "waiting for locator('.notifications-toasts').locator('.notification-toast-container').filter({ has: locator('.codicon-info') }).filter({ hasText: 'All installed extensions are temporarily disabled' })",
      '  locator resolved to 0 elements',
      '  unexpected value "0"',
      '  locator resolved to 0 elements',
      '  unexpected value "0"'
    ],
    timeout: undefined
  },
  [Symbol(step)]: {
    stepId: 'expect@29',
    category: 'expect',
    title: 'expect.not.toHaveCount',
    params: undefined,
    infectParentStepsWithError: undefined,
    boxedStack: undefined,
    location: {
      file: 'C:\\Users\\daves\\confluent_dev\\vscode\\tests\\e2e\\baseTest.ts',
      line: 156,
      column: 39,
      function: 'globalBeforeEach'
    },
    steps: [],
    complete: [Function: complete],
    endWallTime: 1758051504860,
    error: {
      message: 'Error: \x1B[2mexpect(\x1B[22m\x1B[31mlocator\x1B[39m\x1B[2m).\x1B[22mnot\x1B[2m.\x1B[22mtoHaveCount\x1B[2m(\x1B[22m\x1B[32mexpected\x1B[39m\x1B[2m)\x1B[22m\n' +
        '\n' +
        "Locator: locator('.notifications-toasts').locator('.notification-toast-container').filter({ has: locator('.codicon-info') }).filter({ hasText: 'All installed extensions are temporarily disabled' })\n" +
        'Expected: not \x1B[32m0\x1B[39m\n' +
        'Received: \x1B[31m0\x1B[39m\n' +
        'Call log:\n' +
        '  \x1B[2m- expect.not.toHaveCount with timeout 60000ms\x1B[22m\n' +
        "\x1B[2m  - waiting for locator('.notifications-toasts').locator('.notification-toast-container').filter({ has: locator('.codicon-info') }).filter({ hasText: 'All installed extensions are temporarily disabled' })\x1B[22m\n" +
        '\x1B[2m  -   locator resolved to 0 elements\x1B[22m\n' +
        '\x1B[2m  -   unexpected value "0"\x1B[22m\n' +
  ✘  2 [stable] › confluent.spec.ts:11:3 › should activate the extension (2.9s)
        '\x1B[2m  -   unexpected value "0"\x1B[22m\n',
      stack: 'Error: \x1B[2mexpect(\x1B[22m\x1B[31mlocator\x1B[39m\x1B[2m).\x1B[22mnot\x1B[2m.\x1B[22mtoHaveCount\x1B[2m(\x1B[22m\x1B[32mexpected\x1B[39m\x1B[2m)\x1B[22m\n' +
        '\n' +
        "Locator: locator('.notifications-toasts').locator('.notification-toast-container').filter({ has: locator('.codicon-info') }).filter({ hasText: 'All installed extensions are temporarily disabled' })\n" +
        'Expected: not \x1B[32m0\x1B[39m\n' +
        'Received: \x1B[31m0\x1B[39m\n' +
        'Call log:\n' +
        '  \x1B[2m- expect.not.toHaveCount with timeout 60000ms\x1B[22m\n' +
        "\x1B[2m  - waiting for locator('.notifications-toasts').locator('.notification-toast-container').filter({ has: locator('.codicon-info') }).filter({ hasText: 'All installed extensions are temporarily disabled' })\x1B[22m\n" +
        '\x1B[2m  -   locator resolved to 0 elements\x1B[22m\n' +
        '\x1B[2m  -   unexpected value "0"\x1B[22m\n' +
        '\x1B[2m  -   locator resolved to 0 elements\x1B[22m\n' +
        '\x1B[2m  -   unexpected value "0"\x1B[22m\n' +
        '\n' +
        '    at globalBeforeEach (C:\\Users\\daves\\confluent_dev\\vscode\\tests\\e2e\\baseTest.ts:156:39)\n' +
        '    at Object.page (C:\\Users\\daves\\confluent_dev\\vscode\\tests\\e2e\\baseTest.ts:130:7)'
    }
  }
}
Testing stopped early after 1 maximum allowed failures.


  1) [stable] › confluent.spec.ts:11:3 › should activate the extension ─────────────────────────────

    Error: locator.isVisible: Target page, context or browser has been closed

       at ..\utils\sidebarNavigation.ts:22

      20 |   // and if not, click the activity bar item to show it
      21 |   const viewContainer = new ViewContainer(page, "confluent");
    > 22 |   const isVisible = await viewContainer.locator.isVisible();
         |                                                 ^
      23 |   if (!isVisible) {
      24 |     const activityBarItem = new ActivityBarItem(page, "Confluent");
      25 |     await expect(activityBarItem.locator).toBeVisible();

        at openConfluentSidebar (C:\Users\daves\confluent_dev\vscode\tests\e2e\utils\sidebarNavigation.ts:22:49)
        at C:\Users\daves\confluent_dev\vscode\tests\e2e\specs\confluent.spec.ts:12:5
```

The `Target page, context or browser has been closed` seems to point at a bigger issue than checking for the info notification.

(Note this does not affect WSL, as E2E tests still run as expected there.)

### PR DESCRIPTION
**Pull request by shouples**
The main problem was this highlighted part from this screenshot in https://github.com/confluentinc/vscode/issues/2609#issuecomment-3300206479:
image

Where, upon changing the `window.menuStyle` setting on Windows, a system dialog would show up saying the window needed to be reloaded. That combined with this:
https://github.com/confluentinc/vscode/blob/33195f2a1189891b00c68b649ac954c6ff6f2017/tests/e2e/baseTest.ts#L85-L88
...meant we were automatically restarting the (test) VS Code window and losing our `page` context before tests even started.

Closes #2609, confirmed working on Windows locally.
image

### CODE REVIEW

File: tests/e2e/utils/settings.ts [hunk 1]
```diff
@@ -2,11 +2,17 @@ import { ElectronApplication, Page } from "@playwright/test";
...
-  // required for right-click context menu action to delete subject schemas
-  // (see https://code.visualstudio.com/updates/v1_101#_custom-menus-with-native-window-title-bar)
-  "window.menuStyle": "custom",
-};
+// `window.menuStyle` must be set to "custom" for right-click context menu actions (e.g. deleting
+// schemas, generating projects from sidebar resources, etc), but Windows already sets this to
+// inherit the "custom" setting value from `window.titleBarStyle`, so we shouldn't set it or it will
+// require a restart to take effect. (Also, based on our system dialog stubbing, if we updated this
+// on Windows, we would auto-reload the window and lose our Electron/page context, which will cause
+// all sorts of odd test failures.)
```
Comment (shouples) [inline tests/e2e/utils/settings.ts:10]: Maybe in a future branch we adjust how we're stubbing dialogs so we don't get accidentally get into this situation again, but that's a future-me problem.

**Review by flippingbits — APPROVED** [review]
Thanks, @shouples!
